server:
  port: 8081

spring:
  application:
    name: common-service
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://localhost:8888

  datasource:
    url: jdbc:postgresql://localhost:5432/made-for-maid-local
    username: anan
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        default_schema: common_db
        default_batch_fetch_size: 100

  servlet:
    multipart:
      max-file-size: 20MB      # 업로드 파일 하나의 최대 크기
      max-request-size: 100MB   # 전체 요청의 최대 크기 (여러 파일 포함 가능)
