spring:
  application:
    name: made-for-maid

  datasource:
      url: jdbc:postgresql://localhost:5433/made-for-maid-local
      username: anan
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop # ?? none, validate, create, create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true # ??? SQL ?? ??
        default_schema: common_db

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
