### 코드 생성
POST {{gatewayUrl}}/api/common/code/create
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "code": "SHOP_CONCEPT_ANIMAL",
    "displayName": "동물",
    "parentCode": "SHOP_CONCEPT"
}

### 코드 트리 조회
GET {{gatewayUrl}}/api/common/code/tree
Accept: application/json
Authorization: Bearer {{accessToken}}
