### 코드 생성
POST {{gatewayUrl}}/api/common/code/create
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "code": "NEW_CODE",
    "displayName": "New Code Name",
    "description": "Description of the new code",
    "codeOrder": 0
}
