### 코드 생성
POST {{gatewayUrl}}/api/common/code/create
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "code": "STAFF_CONCEPT_BUTLER",
    "displayName": "집사",
    "parentCode": "STAFF_CONCEPT",
    "codeOrder": 1
}

### 코드 트리 조회
GET {{gatewayUrl}}/api/common/code/tree
Accept: application/json
Authorization: Bearer {{accessToken}}
